### ISSUE TITLE
What is the purpose of the TaskType enum

### ISSUE THREAD

**Issue by avcarr2** [nbollis/InstrumentControl#6]
Like in here: 
https://github.com/nbollis/InstrumentControl/blob/1f3e34e3131f31de804b44d4a4bf09a3b745d24d/InstrumentControl/Applications/WholeChargeEnvelopeFragmentationApplication.cs#L22

Why does the initializer need the enum as a parameter? Seems unnecessary to me

**Comment by nbollis** [comment]
Unnecessary remnant of a previous iteration of the design. I can this when you finish working on the program components
